import type { NextPage } from 'next'
import Head from "next/head"
import { AboutMePage } from "../../libs/about-me/about-me"

const AboutMe: NextPage = () => {
    return (
      <div>
        <Head>
          <title>Brad King</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <AboutMePage />
        </div>
    )
  }
  
  export default AboutMe