import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Button } from '@mui/material'
import styles from '../styles/Home.module.scss'
import { HomePage } from '../libs/home/home'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Brad King</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
      </div>
  )
}

export default Home
